name: Deploy Code to S3

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      
      - name: Push Code to S3
        env: 
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
          AWS_CODE_BUCKET: ${{secrets.AWS_CODE_BUCKET}}
        run: |
          export AWS_ACCESS_KEY_ID=${{env.AWS_ACCESS_KEY_ID}}
          export AWS_SECRET_ACCESS_KEY=${{env.AWS_SECRET_ACCESS_KEY}}
          export AWS_DEFAULT_REGION=${{env.AWS_DEFAULT_REGION}}
          aws s3 cp src/ s3:${{env.AWS_CODE_BUCKET}}/ --recursive --sse
          aws s3 cp tsconfig.json s3:${{env.AWS_CODE_BUCKET}}/ --sse
          aws s3 cp package.json s3:${{env.AWS_CODE_BUCKET}}/ --sse
