name: Provision Backend

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      cwd: ./ws-server-tf
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: ${{secrets.AWS_DEFAULT_REGION}}
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2

      - name: Push Code to S3
        run: |
          aws s3 rm s3://${{secrets.AWS_CODE_BUCKET}} --recursive
          aws s3 cp src/ s3://${{secrets.AWS_CODE_BUCKET}}/app/src/ --recursive --sse
          aws s3 cp tsconfig.json s3://${{secrets.AWS_CODE_BUCKET}}/app/ --sse
          aws s3 cp package.json s3://${{secrets.AWS_CODE_BUCKET}}/app/ --sse
          aws s3 cp package-lock.json s3://${{secrets.AWS_CODE_BUCKET}}/app/ --sse

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Clone Infra Repo
        run: |
          git clone https://${{secrets.REPO_ACCESS_TOKEN}}:x-oauth-basic@github.com/PranayPant/ws-server-tf.git
      
      - name: Setup Terraform Env
        run: |
          chmod +x env.sh
          ./env.sh -tG
          ./env.sh -eP
          ./env.sh -tC
        working-directory: ${{env.cwd}}
          
      - name: Init Provisioning
        run: export TF_CLI_CONFIG_FILE=terraform.rc && terraform init
        working-directory: ${{env.cwd}}

      - name: Plan Provisioning
        run: terraform plan -lock=false
        working-directory: ${{env.cwd}}

      - name: Delete Current Autoscaling Group
        run: terraform apply -auto-approve -destroy -lock=false -target=module.asg
        working-directory: ${{env.cwd}}

      - name: Apply Provisioning
        run: terraform apply -auto-approve -lock=false
        working-directory: ${{env.cwd}}
